# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='balance.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rbalance.proto\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\t\"B\n\x11\x42\x61lanceAdjustment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x11\n\tauthToken\x18\x03 \x01(\t\"\x19\n\x07\x42\x61lance\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x32`\n\x0e\x42\x61lanceService\x12\x1d\n\ngetBalance\x12\x03.Id\x1a\x08.Balance\"\x00\x12/\n\radjustBalance\x12\x12.BalanceAdjustment\x1a\x08.Balance\"\x00\x62\x06proto3')
)




_ID = _descriptor.Descriptor(
  name='Id',
  full_name='Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Id.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=33,
)


_BALANCEADJUSTMENT = _descriptor.Descriptor(
  name='BalanceAdjustment',
  full_name='BalanceAdjustment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BalanceAdjustment.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='BalanceAdjustment.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authToken', full_name='BalanceAdjustment.authToken', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=101,
)


_BALANCE = _descriptor.Descriptor(
  name='Balance',
  full_name='Balance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='Balance.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['Id'] = _ID
DESCRIPTOR.message_types_by_name['BalanceAdjustment'] = _BALANCEADJUSTMENT
DESCRIPTOR.message_types_by_name['Balance'] = _BALANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), dict(
  DESCRIPTOR = _ID,
  __module__ = 'balance_pb2'
  # @@protoc_insertion_point(class_scope:Id)
  ))
_sym_db.RegisterMessage(Id)

BalanceAdjustment = _reflection.GeneratedProtocolMessageType('BalanceAdjustment', (_message.Message,), dict(
  DESCRIPTOR = _BALANCEADJUSTMENT,
  __module__ = 'balance_pb2'
  # @@protoc_insertion_point(class_scope:BalanceAdjustment)
  ))
_sym_db.RegisterMessage(BalanceAdjustment)

Balance = _reflection.GeneratedProtocolMessageType('Balance', (_message.Message,), dict(
  DESCRIPTOR = _BALANCE,
  __module__ = 'balance_pb2'
  # @@protoc_insertion_point(class_scope:Balance)
  ))
_sym_db.RegisterMessage(Balance)



_BALANCESERVICE = _descriptor.ServiceDescriptor(
  name='BalanceService',
  full_name='BalanceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=130,
  serialized_end=226,
  methods=[
  _descriptor.MethodDescriptor(
    name='getBalance',
    full_name='BalanceService.getBalance',
    index=0,
    containing_service=None,
    input_type=_ID,
    output_type=_BALANCE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='adjustBalance',
    full_name='BalanceService.adjustBalance',
    index=1,
    containing_service=None,
    input_type=_BALANCEADJUSTMENT,
    output_type=_BALANCE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BALANCESERVICE)

DESCRIPTOR.services_by_name['BalanceService'] = _BALANCESERVICE

# @@protoc_insertion_point(module_scope)
